// Generated by tools/ogdocgen from the OpenGate documentation. DO NOT EDIT.
// context: connector-function
//
// Source pages:
//   content/api/debugging/logger_api.md
//   content/api/device_integration/connector_functions/core_javascript_api/concatenated.md
//   content/api/device_integration/connector_functions/core_javascript_api/cryptography.md
//   content/api/device_integration/connector_functions/core_javascript_api/cryptography_internal.md
//   content/api/device_integration/connector_functions/core_javascript_api/entity.md
//   content/api/device_integration/connector_functions/core_javascript_api/inner_collections.md
//   content/api/device_integration/connector_functions/core_javascript_api/javascript_api.md
//   content/api/device_integration/connector_functions/core_javascript_api/operation.md
//   content/api/device_integration/connector_functions/core_javascript_api/operation_steps.md
//   content/api/device_integration/connector_functions/core_javascript_api/provision.md
//   content/api/device_integration/connector_functions/core_javascript_api/utils.md
//   content/api/device_integration/connector_functions/core_javascript_api/utils_internal.md
//   content/api/device_integration/connector_functions/protocol_apis/coap.md
//   content/api/device_integration/connector_functions/protocol_apis/dlms.md
//   content/api/device_integration/connector_functions/protocol_apis/dlms_gas.md
//   content/api/device_integration/connector_functions/protocol_apis/http.md
//   content/api/device_integration/connector_functions/protocol_apis/icmp.md
//   content/api/device_integration/connector_functions/protocol_apis/icmp_response.md
//   content/api/device_integration/connector_functions/protocol_apis/iec102.md
//   content/api/device_integration/connector_functions/protocol_apis/iec102_internal.md
//   content/api/device_integration/connector_functions/protocol_apis/kite.md
//   content/api/device_integration/connector_functions/protocol_apis/mqtt.md
//   content/api/device_integration/connector_functions/protocol_apis/snmp.md
//   content/api/device_integration/connector_functions/protocol_apis/ssh.md
//   content/api/device_integration/connector_functions/protocol_apis/telnet.md
//   content/api/device_integration/connector_functions/protocol_apis/websocket.md
//
// Regenerate: go run ./tools/ogdocgen -docs <odm-documentation-hugo> -out internal/typegen/templates

// ── Plain functions ─────────────────────────────────────────────────────────

/** **Activate the target operation selected with parameters of the context** */
declare function activate(): any;

/**
 *  Adds datapoint to specified datastream in the collection object, if datastream does not exist, it creates the datastream.
 *  @deprecated Build collections with the `collection` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function addOgCollectionDp(datapoint: any, ogCollection: any, datastreamId: string, feed: string): any;

/**
 *  Used in Request or Response connector functions to define a concatenated Collection action.
 *  @deprecated Use `cf.collection` instead. Note the arguments are in the opposite order: `cf.collection` takes the criteria first and the payload second.
 */
declare function collectCF(collectionData: any, collectionFunctionCriteria: string): any;

/**
 *  Decrypt an encrypted string with the configuration established by the datastream of the organization
 *  @deprecated Use `utils.odm.decryptString` instead.
 */
declare function decryptString(encryptedValue: string, datastreamConfiguration: string, organizationName: string): string;

/**
 *  Encrypt an original string with the configuration established by the datastream of the organization
 *  @deprecated Use `utils.odm.encryptString` instead.
 */
declare function encryptString(originalValue: string, datastreamConfiguration: string, organizationName: string): string;

/**
 *  Extract from the first entity of entities array specified datastream "value" field value.
 *  @deprecated Use `utils.odm.entitiesValue` instead. It moved to `utils` because, unlike the rest of this group, it acts across several entities rather than one.
 */
declare function entitiesValue(entities: any[], datastream: OGDatastreamID, index?: number): any;

/**
 *  Extract from entity specified datastream "at" field value.
 *  @deprecated Use `entity._at` instead — the entity is the receiver, so the first argument goes away. The same method works on `gateway`.
 */
declare function entityAt(entity: any, datastream: OGDatastreamID, index?: number): any;

/**
 *  Extract from entity specified datastream "date" field value.
 *  @deprecated Use `entity._date` instead — the entity is the receiver, so the first argument goes away. The same method works on `gateway`.
 */
declare function entityDate(entity: any, datastream: OGDatastreamID, index?: number): any;

/**
 *  Extract from entity specified datastream "source" field value.
 *  @deprecated Use `entity._source` instead — the entity is the receiver, so the first argument goes away. The same method works on `gateway`.
 */
declare function entitySource(entity: any, datastream: string, index?: number): any;

/**
 *  Extract from entity specified datastream "sourceInfo" field value.
 *  @deprecated Use `entity._sourceInfo` instead — the entity is the receiver, so the first argument goes away. The same method works on `gateway`.
 */
declare function entitySourceInfo(entity: any, datastream: string, index?: number): any;

/**
 *  Extract from entity specified datastream "value" field value.
 *  @deprecated Use `entity._value` instead — the entity is the receiver, so the first argument goes away. The same method works on `gateway`.
 */
declare function entityValue(entity: any, datastream: OGDatastreamID, index?: number): any;

/**
 *  Calculates the address type from a given address
 *  @deprecated Use `utils.odm.getAddressTypeFromAddress` instead.
 */
declare function getAddressTypeFromAddress(address: string): any;

/** **Builds and returns the request the device must send to respond to the operation** */
declare function getRequest(): any;

/**
 *  Executes specified request with specified payload.
 *  @deprecated Use the `http.client` object instead. It is not a single call: the object is configured first and then one of its methods — `get`, `post`, `put`, `patch`, `delete` or `request` — is invoked.
 */
declare function httpRequest(request: any, payload?: any): any;

/**
 *  Creates Info level logging messages. It concatenates msg parameters in the final string to be logged.
 *  @deprecated Use `logger.debug` instead, or another level of the `logger` object where it fits better.
 */
declare function log(...msg: any[]): any;

/**
 *  Creates OG collection main object.
 *  @deprecated Build collections with the `collection` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogCollection(datastreams: any[], device: string, version: string): any;

/**
 *  Creates OG collection datapoint object.
 *  @deprecated Build collections with the `collection` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogCollectionDp(value?: any, at?: number, source?: string, sourceInfo?: string): any;

/**
 *  Creates OG collection datastream object.
 *  @deprecated Build collections with the `collection` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogCollectionDs(datastreamId?: string, feed?: string, datapoints?: any[]): any;

/**
 *  Creates OG response object
 *  @deprecated Build operation responses with the `response` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogResponse(id: string, name: string, deviceId: string, resultCode: string, resultDescription: string, steps: any[], timestamp: string, trustedBoot: string, version: string): any;

/**
 *  Creates OG step object used in opengate response object.
 *  @deprecated Build operation responses with the `response` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogStep(name?: string, result?: string, description?: string, stepResponseList?: string): any;

/**
 *  Creates OG step response object, used in step object.
 *  @deprecated Build operation responses with the `response` object instead. The object is not a function-for-function replacement: it simplifies what these globals did by hand.
 */
declare function ogStepResponse(name?: any, value?: any): any;

/**
 *  Publish specified payload for specified topic and device.
 *  @deprecated Use the `mqtt` object instead: set `mqtt.topic` and `mqtt.device`, then call `mqtt.publish`.
 */
declare function publishOnTopic(payload: any, topic: string, deviceId: string): any;

/**
 *  Used in Request connector functions to define a concatenated Response action.
 *  @deprecated Use `cf.response` instead. Note the arguments are in the opposite order: `cf.response` takes the criteria first and the payload second.
 */
declare function responseCF(responseData: any, responseFunctionCriteria: string): any;

/**
 *  Send message to opened websocket
 *  @deprecated Use the `websocket` object instead, which has to be configured before calling `websocket.sendMsg`.
 */
declare function webSocketMsg(payload: any, deviceId: string): any;

// ── Objects ─────────────────────────────────────────────────────────────────

declare const cf: {
  /**
   *  Sets a call for a COLLECTION connector function, if there is one that matches the south criteria indicated in `collectionFunctionCriteria`, setting its input payload to the value of `collectionPayload`.
   */
  collection(collectionFunctionCriteria: string, collectionPayload: any): void;
  /**
   *  Extract from operationObj deviceId field. This function could be used in REQUEST CFs, when the payload is Operation Request json.
   */
  operationDeviceId(operationObj: any): string;
  /**
   *  Extract from operationObj id field. This function could be used in REQUEST CFs, when the payload is Operation Request json.
   */
  operationId(operationObj: any): string;
  /**
   *  Extract from operationObj name field. This function could be used in REQUEST CFs, when the payload is Operation Request json.
   */
  operationName(operationObj: any): string;
  /**
   *  Extract from operationObj *parameters* field. This function could be used in REQUEST CFs, when the payload is Operation Request json.
   */
  operationParameters(operationObj: any): any;
  /**
   *  Extract from operationObj timestamp field. This function could be used in REQUEST CFs, when the payload is Operation Request json.
   */
  operationTimestamp(operationObj: any): number;
  /**
   *  Sets a call for a RESPONSE connector function, if there is one that matches the south criteria indicated in `responseFunctionCriteria`, setting its input payload to the value of `responsePayload`.
   */
  response(responseFunctionCriteria: string, responsePayload: any): void;
};

declare const coap: {
  server: {
    /** Received http request body (the same content as the `payload` property) */
    body: any;
    /** Received http request headers */
    headers: any;
    /**
     *  Object to be used to define http response to be sent when CF finishes
     *  Default: {}
     */
    response: any;
    /** Received http request uri (without host) */
    uri: string;
  };
};

declare const collection: {
  /**
   *  Builds a datapoint object and adds it to the specified datastream in the datastreams list in the `collection` global object.
   */
  addDatapoint(datastreamId: OGDatastreamID, value?: any, at?: number, source?: string, sourceInfo?: string): void;
  /**
   *  Searches for a datapoint value for the specified datastreamId. It is possible to specify the datapoint index inside the datastream. If not found, a null value will be returned.
   */
  getValue(datastream: OGDatastreamID, dpIndex?: number): any;
  /**
   *  Sends a collection message to the OpenGate's collection messages flow using the datastreams list in the `collection` global object, after that this list is cleaned.
   */
  send(): void;
  /**
   *  Sets the feed name to a specific datastream in the datastreams list in the `collection` global object.
   */
  setFeed(datastreamId: OGDatastreamID, feed: string): void;
};

declare const crypt: {
  aes: {
    /** Decrypt the `data` using the selected AES `algorithm` with the provided shared `key`. */
    decrypt(algorithm: string, key: Uint8Array, ivParameterSpec: any, data: Uint8Array): Uint8Array;
    /** Encrypt the `data` using the selected AES `algorithm` with the provided shared `key`. */
    encrypt(algorithm: string, key: Uint8Array, ivParameterSpec: any, data: Uint8Array): Uint8Array;
  };
  hmac: {
    /**
     *  Create a hash from provided string using provided algorithm.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    hash(algorithm: any, data: string, key: Uint8Array): any;
    /** Create a hash from provided string using sha256. */
    sha256(data: string, key: Uint8Array): any;
    /** Create a hash from provided string using sha512. */
    sha512(data: string, key: Uint8Array): any;
  };
};

declare const dlms: {
  /** Applicable for normal gets. */
  addAttr(classId: any[], obisCode: string, attrId: number): any;
  /** `addMethod()` is used for `method()` function. */
  addMethod(classId: any[], obisCode: string, methodId: string, type: string, value: string): any;
  /** Opens DLMS connection (default via TCP transport). */
  connect(): any;
  /** Close the DLMS connection. */
  disconnect(): any;
  /**
   *  Executes a multi DLMS get attribute request with the previously specified payload (`addAttr(classId, obisCode, attrId)`).
   */
  get(descriptive?: boolean, forceWithoutList?: boolean): any[];
  /** Extract the compact data serialized in a byte array according to the description given. */
  getCompactData(typeDescription: any, value: any, descriptive?: boolean, italianMode?: boolean): any;
  /**
   *  Extract the `Date` of a _dateTime_ object or an `octet-string`. Some _dateTime_ objects or `octet-string` may not contain a complete date and this method will return a date that may not be as accurate as you expect. You should check the _dateTime_ object for unspecified value.
   */
  getDate(value: any): Date;
  /**
   *  Extract the _dateTime_ object of a `Date` or an `octet-string`. The resulting _dateTime_ objects generated from a `Date` will use UTC time specifying a deviation of `0`. If you need something else construct the _dateTime_ object manually.
   */
  getDateTime(value: any): any;
  /** Returns the current invocation counter of the ciphering. */
  getInvocationCounter(): number;
  /**
   *  Sets the invocation counter of the ciphering to the next value of the received frame counter. This is used for devices that maintain two separate frame counters (one for transmit and one for receive). Usually the current _Management Frame Counter - On-line_ is received in a _CompactFrame_ notification and that value is the one that needs to be passed to this function for that device.
   */
  initializeNextFrameCounter(currentFrameCounter: number): any;
  /**
   *  Executes a multi DLMS method (or action) request with the previously specified payload (`addMethod(classId, obisCode, methodId, type, value)`).
   */
  method(descriptive?: boolean): any[];
  /**
   *  Executes a multi DLMS set attribute request with the previously specified payload (`addAttr(classId, obisCode, attrId, type, value)`).
   */
  set(descriptive?: boolean): any[];
  /** Get _dateTime_ object with all its fields set to not specified. */
  undefinedDateTime(): any;
  /** Get _dateTime_ object with all its fields set to not specified. */
  unspecifiedDateTime(): any;
};

declare const dlms_gas: {
  /**
   *  It executes specified standard `dlms` call (`get`, `set`, `method`). It will use the `dType` and `uType` for `msRaw` collection. It will return an object with the result from dlms standard function or with the error message. This method is just utility and is not intended to be used directly. Instead it must be used `dlms_gas.get`, `dlms_gas.set`, `dlms_gas.method` or `dlms_gas.getByRange`.
   */
  _exec(callType: string, dType: number, uType: number): any;
  /**
   *  Used at the end of the script to send collected data for meter entity, cell enity and organization entity. Internally it calls to specific behavior `collect` method.
   */
  collect(): any;
  /**
   *  Changes the default behavior to a custom one. Internall it set `dlms_gas.behaviorName` property to `"custom"` and `dlms_gas.custom` property with the behavior provided as argument.
   */
  customBehavior(behavior?: any): any;
  /**
   *  Decodes received payload after identifying the template and collects data. Internally it calls to behavior specific `decode` method. See `DLMS Manufacturer Behavior` section below for full specification of that method.
   */
  decode(customTemplate?: any, descriptive?: boolean): any;
  /**
   *  It wrapes `dlms.get` calls adding extra behavior. `dType` and `uType` will be used for `msRaw` collection. The `dlms.get` response will be flattened in order to store the values in a single object. See examples below.
   */
  get(dType: number, uType: number): any;
  /**
   *  It retrieves values by range using `dlms.get` with selective access. It retrieves all the values within the range, even if the device returns values in multiple pages. In case of any page retrieval fails, the error will be added to the error property and the response will be "success" for the rest of the pages.
   */
  getByRange(classId: number, obis: string, attrId: number, accessSelector: number, paramClassID: number, paramObis: string, paramAttrId: number, rangeType: string, rangeFrom: number, rangeTo: number, maxRangePerPage: number, dType: number, uType: number): any;
  /**
   *  Initializes the DLMS Gas API context. It loads provisioned and collected data from meter entity and provisioned configuration data from configuratiion entity if it is found. By default it uses the meter's organization name to find created configuration entity, if it was created with different name it must be passed as argument.
   */
  init(confEntityName?: string): any;
  /**
   *  It wrapes `dlms.method` calls adding extra behavior. `dType` and `uType` will be used for `msRaw` collection. The `dlms.method` response will be flattened in order to store the values in a single object. See examples below.
   */
  method(dType: number, uType: number): any;
  /**
   *  Executes the full session flow. Internally it calls to behavior specific `pendingActions` method. See `DLMS Manufacturer Behavior` section below for full specification of that method.
   */
  pendingActions(): any;
  /**
   *  It wrapes `dlms.set` calls adding extra behavior. `dType` and `uType` will be used for `msRaw` collection. The `dlms.set` response will be flattened in order to store the values in a single object. See examples below.
   */
  set(dType: number, uType: number): any;
  behavior: {
    /**
     *  Internall utility to calculate recursively the behavior chain. It is called from `dlms_gas.init` and it will return a `Set` with all behaviors to be checked when a function or property is called. It will take into account that specified behavior exists, if not it will return `default` behavior as last element of the chain. Something similiar will happen if there is a circular baseBehavior reference.
     */
    calculateChain(behaviorName?: string, visited?: any): any;
    /**
     *  Returns function from behavior chain in order to call it. It will return the function if exists in any behavior in the chain, if not it will empty function.
     */
    function_(functionName?: string): any;
    /**
     *  Calculates and returns behavior name from manufacturer parameter (Not case session). This method is called from `dlms_gas.init` function only if `dlms_gas.behaviorName` is null.
     */
    getName(manufacturer?: string): any;
    /**
     *  Returns property value from behavior chain in order to call it. It will return the property value if exists in any behavior in the chain, if not it will return null.
     */
    property(propertyName?: string): any;
  };
  config: {
    /** Internal utility used to initialize the API key. */
    __initApiKey(apiKey: string): any;
  };
  default_: {
    /**
     *  Apn configuration operation logic. Configures the SIM APN and PLMN code on the device and processes the operation response.
     */
    apnConfig(op: any): any;
    /**
     *  Orchestrates automatic data retrieval functions. These functions retrieve data from the device depending on last collected data and new received data. Following functions are called in order:
     */
    automaticActions(): any;
    /**
     *  Called at then end of `pendingActions` function. In this case (`default` behavior) it is empty.
     */
    closeConnection(): any;
    /**
     *  Sends the gathered datapoints for the device, cell, and organizational unit. It takes into account if `dls_gas.devCollection`, `dls_gas.cellCollection` or `dls_gas.uoCollection` are defined and they have `identifier` field is defined.
     */
    collect(): any;
    /**
     *  Collects the billing period data snapshot. Receives an with the values of decoded billing period snapshot:
     */
    collectBillingPeriodSnapshotData(billingPeriodData: any): any;
    /**
     *  Collects from received daily profiles with specified source and sourceInfo. Each element of array must be an object with the following fields:
     */
    collectDailyLoadProfilesArray(loadProfiles: any[], source?: string, sourceInfo?: any): any;
    /**
     *  Decodes a 16-bit diagnostic value into individual status flags that are collected with specified at, source and sourceInfo.
     */
    collectDiagnostic(diagnostic: number, at?: number, source?: string, sourceInfo?: any): any;
    /** Collects an array of hourly diagnostics values with at time as reference. */
    collectHourlyDiagnostics(diagnosticsArray: any[], unixTime: any): any;
    /** Collects an array of hourly volume increments with at time as reference. */
    collectHourlyVolumes(incsArray: any[], at: number): any;
    /**
     *  Internal utility to collect raw messages. It adds msRaw datapoint to device, cell and organizational unit collections. Datapoint is composed by provided arguments.
     */
    collectMsRaw(mType: number, payload: string, payloadSize: number): any;
    /**
     *  Decodes an 8-bit network status integer value into individual flags and adds it to the device collection.
     */
    collectNetworkStatus(networkStatus: number, at?: number): any;
    /**
     *  Transforms and collects received array of two numbers into an array of two bytes hexadecimal string.
     */
    collectTarifPlan(tariffPlann: any[], at?: number): any;
    /**
     *  Comms bat status retrieval operation logic. Retrieves battery status and communication statistics from the device and processes the operation response.
     */
    commsBatStatus(op: any): any;
    /**
     *  Initializes the dlms client parameters for sending requests to the device. This method is called from `dlms_gas.init` function.
     */
    configClient(): any;
    /**
     *  Automatically provisions a new NBIoT Cell entity in Opengate if it doesn't exist. It uses `NBcellID` as entity name.
     */
    createCellIfNecessary(): any;
    /** Converts a JavaScript `Date` object into DLMS `octet-string` format for date (5 bytes). */
    dateToDateOctet(date: Date): any;
    /** Converts a JavaScript `Date` object into DLMS `octet-string` format for time (4 bytes). */
    dateToTimeOctet(date: Date): any;
    /**
     *  The main entry point for Compact Frame decoding. It identifies the correct template based on the `templateId` in the context (or it uses the provided `customTemplate`), performs the decoding, and triggers the collection logic.
     */
    decode(customTemplate: any, descriptive: boolean): any;
    /**
     *  Decodes a 6-byte array into a descriptive firmware version string including version numbers, build commit (hex), and date.
     */
    decodeFw(fwBytes: number[]): any;
    /**
     *  Internal function that executes the actual DLMS `set` operations to apply push event configurations.
     */
    doPushEventConfiguration(event: number, conf: any): any;
    /** Encodes an IP address and port into a 22-byte octet-string for push configuration. */
    encodeIpPort(ip: string, port: number): any;
    /**
     *  Event DLMS schedule array generation logic. Generates the event schedule array for push events configuration. Adds the 4 events with corresponding periodicity and hour specification including disabled events.
     */
    eventScheduleArray(scheduleData: any): any;
    /**
     *  FOTA configuration operation logic. It manages specific scheduling, fota process initialization, blocks transfers by sessions and different process status management. It manage the operation status allong all the process.
     */
    fota(op: any): any;
    /**
     *  Recalculates and returns blocks map according to the expectedNumberOfBlocks calculated at the FOTA operation beginig. If received array shorter than expected it is filled with `false` values. If it is larger, it is truncated to the expected number of blocks.
     */
    fotaAdjustBlocks(imageTransferBlocksMap: any[], expectedNumberOfBlocks: number): any;
    /**
     *  Executes the actual transmission of a single firmware block calling `dlms.sendFotaPage` method. It increase success and error counters.
     */
    fotaBlockTransfer(blockIndex: any, bundleName: any, bundleVersion: any, deploymentName: any, deploymentVersion: any): any;
    /**
     *  Orchestrates the transmission of multiple firmware blocks in a single session, respecting the maximum messages allowed for the current ECL. It manages specially first and last block sent to update operation status. It also manages errors per session.
     */
    fotaBlocksTransfer(op: any, blocksStatusMap: any): any;
    /**
     *  Calculates the unique image identifier based on KDL, hashtag, and activation date. It adds at the beginning of the identifier follwing bytes `014D`.
     */
    fotaCalculateIdentifier(op: any): any;
    /**
     *  Verifies if the device is correctly configured for FOTA (valid block size and FOTA enabled). It updates operation status according to the validation.
     */
    fotaCheckAllowed(op: any): any;
    /**
     *  Aborts the FOTA process if the number of consecutive bad sessions reaches the maximum allowed threshold and throws an error. It uses `badSessionsCounter` and `maxBadSessions` from `dlms_gas.config`.
     */
    fotaCheckBadSessions(): any;
    /** Just checks session errors rate and updates bad sessions counter. */
    fotaCheckSessionBlocksErrors(): any;
    /**
     *  Internal function used to continue FOTA operation from different sessions: it manage different process status, sends blocks and finalizes operation according to final status (including device default scheduling).
     */
    fotaContinueProcess(op: any): any;
    /**
     *  Function intended to invoke image activation DLMS method, but actually is empty function in default behavior. It can be implemented in specific behaviors.
     */
    fotaImgActivate(op: any): any;
    /**
     *  Invokes image transfer process initiation DLMS method and calculates the total number of blocks based on the firmware size and configured block size. It updates operation status.
     */
    fotaImgTransferInitiate(op: any): any;
    /**
     *  Function intended to invoke image verification DLMS method, but actually is empty function in default behavior. It can be implemented in specific behaviors.
     */
    fotaImgVerify(op: any): any;
    /**
     *  Restores the default push strategy schedule after the FOTA process is finished or cancelled. It updates operation status.
     */
    fotaRestoreDefaultSchedule(op: any): any;
    /**
     *  Temporary updates the push strategy schedule to a more aggressive frequency (every hour) during the FOTA process to speed up block transmission. It updates operation status.
     */
    fotaScheduleForFota(op: any): any;
    /**
     *  Internal function used to complete first steps of FOTA operation: device status validation, device special scheduling and fota process initialization in the meter.
     */
    fotaStartProcess(op: any): any;
    /** It retrieves CF22 and updates session data to continue with FOTA proess. */
    fotaStateFromCf22(op: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 0. Actually it calls `fotaStatusUnknown` function because this function is not supposed to be executed.
     */
    fotaStatus0(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 1. Try to send pending blocks or call image verification function.
     */
    fotaStatus1(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 2. In `default` behavior it does nothing.
     */
    fotaStatus2(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 3. It just calls to `fotaImgActivate` function.
     */
    fotaStatus3(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 4. It finishes the FOTA process with image verification error.
     */
    fotaStatus4(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 5. In `default` behavior it does nothing.
     */
    fotaStatus5(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 6. Asks to device for new firmware data, restores default scheduling and finlizes FOTA operation.
     */
    fotaStatus6(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve status 7. It finishes the FOTA process with image activation error.
     */
    fotaStatus7(op: any, fotaState: any): any;
    /**
     *  Executed when the devices Compact Frame 22 retrieve an unexpected status. In `default` behavior it just incresaes bad sessions counter.
     */
    fotaStatusUnknown(op: any, fotaState: any): any;
    /**
     *  Function that depending on fotaState (process status and blocks maps) updates operation lost steps.
     */
    fotaUpdateLostSteps(fotaState: any, op: any): any;
    /** Updates the internal block transmission counter based on the blocks retrieved form CF 22. */
    fotaUpdateSuccessBlocksFromDevice(imageTransferBlocksMap: any[]): any;
    /**
     *  From an array with hourly data (volumes, diagnostics...) and with refTime as reference, build an array with the at time of each increment.
     */
    getHourlyArrayWithAt(hourlyArray: any[], refTime: number): any;
    /**
     *  Returns the DLMS date octet-string representing the periodicity for push event schedulation. It takes into account both `period` and `time`.
     */
    getPeriodictyOctet(period: string, time: string): any;
    /**
     *  Search in passed operation object if the step is already completed. If checkInCurrentResponse is not specified, it will check only in steps completed in the operation. If checkInCurrentResponse is specified and it is true, it will check also in the steps added in current execution.
     */
    getStepByName(op: any, stepName: string, checkInCurrentResponse: boolean): any;
    /**
     *  Returns the DLMS time octet for push event schedulation. It takes into account both `period` and `time`.
     */
    getTimeOctet(period: string, time: string): any;
    /**
     *  Horly values retrieval operation logic. Retrieves hourly incremental volume values from the device by range and processes the operation response.
     */
    hourlyValues(op: any): any;
    /**
     *  Function called from `dlms_gas.decode` after decoding 47 compact frame from received notification. Initialize parameters to be used later and collects received fields.
     */
    initAndCollectCf47(data: any): any;
    /**
     *  Function called from `dlms_gas.decode` after decoding 48 compact frame from received notification. Initialize parameters to be used later and collects received fields.
     */
    initAndCollectCf48(data: any): any;
    /**
     *  Function called from `dlms_gas.decode` after decoding 49 compact frame from received notification. Initialize parameters to be used later and collects received fields.
     */
    initAndCollectCf49(data: any): any;
    /**
     *  Function called from `dlms_gas.decode` after decoding 51 compact frame from received notification. Initialize parameters to be used later and collects received fields.
     */
    initAndCollectCf51(data: any): any;
    /**
     *  Function called from `dlms_gas.decode()` after decoding 97 compact frame from received notification. Initialize parameters to be used later and collects received fields.
     */
    initAndCollectCf97(data: any): any;
    /**
     *  Dispatches and executes active operations from the Opengate platform. Retrieves all alive operations for the device using [Operations JS Api](/api/device_integration/connector_functions/core_javascript_api/operation/). It iterates through `supportedOps` and executes the process for any matching active operation.
     */
    operations(): any;
    /**
     *  The main entry point for a standard communication session. It orchestrates the actions to be performed in a session. It uses `dlms_gas.actions` object to determine which actions to perform.
     */
    pendingActions(): any;
    /**
     *  Orchestrates periodic data retrieval functions. These functions retrieve data from the device periodically:
     */
    periodicActions(): any;
    /**
     *  Push configuration operation logic. Configures the push communication strategy (Compact Frame selection, platform address/port, and scheduling) for the four supported push events and process the operation response.
     */
    pushStrategy(op: any): any;
    /**
     *  Non metrological logs retrieval operation logic. Retrieves non-metrological event logs from the device by range and processes the operation response.
     */
    requestNonMetroLogs(op: any): any;
    /**
     *  Reset diagnostic operation logic. Resets the device's diagnostic status flags by executing the corresponding DLMS method and process the operation response.
     */
    resetDiagnostic(op: any): any;
    /**
     *  This method is used when received compact frame does not contain `onlineFrameCounter` and it is necessary to request it to the device in order to set correct values for next requests.
     */
    restoreOnlineFrameCounter(): any;
    /**
     *  If the device does not communicate in last days it will ask for all missing daily profiles.
     */
    retrieveDailyProfiles(): any;
    /**
     *  Retrieves one-time device information. It will check if `device.software` datastream is not collected or `force` parameter is `true`. If so it will retrieve following data:
     */
    retrieveInitialData(force: boolean): any;
    /**
     *  Retrieves missing metrological events from the device by range, starting from the last collected counter.
     */
    retrieveMetrologicalEvents(): any;
    /**
     *  Retrieves configuration for all push events (1-4) configuration. It will check for each event if `confCFx` datastream is not collected or `force` parameter is `true`. If so it will retrieve push event configuration.
     */
    retrievePushEventsConfigurations(force: any): any;
    /**
     *  Retrieves periodically communication statistics (Signal Power, RSRQ, RSRP, ECL, Battery remaining time....). It will check `statisticsRefDs` datastreams `at` value and if the data is too old (using `periodicDataAgeMillis` as reference).
     */
    retrieveStatistics(force: boolean): any;
    /** Returns converted raw RSRQ to dB/dBm following standard dlms specfication. */
    rsrpFromRaw(raw: any): any;
    /** Returns converted raw RSRQ to dB/dBm following standard dlms specfication. */
    rsrqFromRaw(raw: any): any;
    /** Checks drift and synchronizes device time. */
    setClock(): any;
    /** Converts raw CSQ value to dBm following DLMS specification. */
    signalQualityFromRaw(raw: number): any;
    /** Decodes the communication strategy from two bits. */
    strategy(b1: number, b0: number): any;
    /** Decodes TAU timer to seconds following DLMS specification. */
    tauInSecondsFromRaw(raw: any): any;
    /** Decodes raw TMR to seconds following dlms specfication. */
    tmrInSecondsFromRaw(raw: any): any;
    /**
     *  Valve managment operation logic. Executes valve Open/Close commands and process the operation response.
     */
    valveManagement(op: any): any;
  };
  honeywell: {
    /** Graceful disconnect via DLMS method specific for Honeywell devices. */
    closeConnection(): any;
    /**
     *  Event DLMS schedule array generation logic. Generates the event schedule array for push events configuration. Adds just the events not disabledwith corresponding periodicity and hour specification.
     */
    eventScheduleArray(scheduleData: any): any;
    /**
     *  Specific statistics retrieval for Honeywell devices, excluding some attributes not supported by these devices.
     */
    retrieveStatistics(force: any): any;
    /** Overrides the default TAU conversion to return directlty the raw value. */
    tauInSecondsFromRaw(raw: any): any;
    /** Overrides the default TMR conversion to return directlty the raw value. */
    tmrInSecondsFromRaw(raw: any): any;
  };
  pietro: {
    /** Specific firmware decoding for Pietro devices. It returns a simplified version string. */
    decodeFw(fwBytes: any): any;
  };
  spark: {
    /** Calculates the unique image identifier based on KDL, hashtag, and activation date. */
    fotaCalculateIdentifier(op: any): any;
    /**
     *  Invokes FOTA image verify DLMS method. It updates the operation status accordingly to the response
     */
    fotaImgVerify(op: any): any;
  };
};

/** Accessor methods carried by `entity`, intersected into its declaration. */
interface OGEntityMethods {
  /** Extract from entity specified datastream “at” field value using parameters */
  _at(datastream: string, index: any): any;
  /** Extract from entity specified datastream date field value using parameters */
  _date(datastream: string, index: any): any;
  /** Extract from entity specified datastream “source” field value using parameters */
  _source(datastream: string, index: any): any;
  /** Extract from entity specified datastream “sourceInfo” field value using parameters */
  _sourceInfo(datastream: string, index: any): any;
  /** Extract from entity specified datastream “value” field value using parameters */
  _value(datastream: string, index: any): any;
}

declare const http: {
  client: {
    /**
     *  Used to set custom https context, alias to be used for keystore
     *  Default: null
     */
    alias: string;
    /**
     *  Response body
     *  Default: null
     */
    body: any;
    /**
     *  Used to set custom https context, certificate content
     *  Default: null
     */
    certificate: string;
    /**
     *  Overrides default client version configured
     *  Default: null
     */
    clientVersion: string;
    /**
     *  Request headers in json format
     *  Default: null
     */
    headers: any;
    /**
     *  One of http methods: POST, GET, ...
     *  Default: null
     */
    method: string;
    /**
     *  Used to set custom https context, private key content
     *  Default: null
     */
    privateKey: string;
    /**
     *  Overrides default redirection policy
     *  Default: null
     */
    redirectPolicy: string;
    /**
     *  Overrides default timeout configured. Defined in seconds
     *  Default: null
     */
    timeOut: number;
    /**
     *  Request uri
     *  Default: null
     */
    uri: string;
    /** Performs DELETE using defined configuration. Overrides defined `method`. */
    delete_(): any;
    /** Performs GET using defined configuration. Overrides defined `method`. */
    get(): any;
    /** Performs PATCH using defined configuration. Overrides defined `method`. */
    patch(): any;
    /** Performs POST using defined configuration. Overrides defined `method`. */
    post(): any;
    /** Performs PUT using defined configuration. Overrides defined `method`. */
    put(): any;
    /** Performs configured http request. `method` property must be defined. */
    request(): any;
  };
  server: {
    /** Received http request body (the same content as the `payload` property) */
    body: any;
    /** Received http request headers */
    headers: any;
    /**
     *  Object to be used to define http response to be sent when CF finishes
     *  Default: {}
     */
    response: any;
    /** Received http request uri (without host) */
    uri: string;
  };
};

declare const icmp: {
  /**
   *  Decide if the request is asynchronous (true) or synchronous (false).
   *  Default: true
   */
  async: boolean;
  /**
   *  IP address to send PING.
   *  Default: (*)
   */
  ip: string;
  /**
   *  Number of PING delivery retries.
   *  Default: 5
   */
  retries: number;
  /**
   *  Timeout in milliseconds of retry.
   *  Default: 2500
   */
  timeout: number;
  /** Send PING using the properties of the `icmp object`: */
  send(): any;
};

declare const iec102: {
  /**
   *  Internal array with the list of ASDUs to be executed. It must be initialized before connecting
   */
  asdus_asdusToExec: any[];
  /** IP address to connect. */
  ip: string;
  /**
   *  Specifies if secure protocol must be used
   *  Default: false
   */
  isTls: boolean;
  /** Mandatory parameter used as part of IEC102 protocol */
  linkAddress: number;
  /** Manufacturer code->name map */
  manufacturerCodeName: any;
  /** Parameter used when connection is done with a data call through some caller */
  msisdn: string;
  /** Parameter used when connection is done with a data call through some caller */
  password: string;
  /** Port to connect */
  port: number;
  /** Parameter used when connection is done with a data call through some caller */
  portConfig: string;
  /**
   *  Internally used parameter to keep ASDUs execution status
   *  Default: Current
   */
  readingState: string;
  /**
   *  It will be used as reference time for period calculation and as datapoints 'at' value
   *  Default: Current
   */
  referenceTime: number;
  /**
   *  Number of retries.
   *  Default: 5
   */
  retries: number;
  /** It will be used as datapoints 'source' value */
  source: string;
  /** It will be used as datapoints 'sourcesInfo' value */
  sourcesInfo: string;
  /**
   *  Timeout in milliseconds.
   *  Default: 30000
   */
  timeout: number;
  /** Mandatory parameter used as part of IEC102 protocol */
  useMeasurePoint: number;
  /** Mandatory parameter used as part of IEC102 protocol */
  usePasswordAccess: number;
  /** Parameter used when connection is done with a data call through some caller */
  userName: string;
  /**
   *  Auxiliary function internally used to calculate carrier value.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  carrier(): number;
  /**
   *  There is a `connect` method used to establish the connection with the device. When this method is called, it internally completes several actions:
   */
  connect(registerType: any): any;
  /** This method is special case for GSM connection. */
  connectWithEndpoints(endpoints: any[]): any;
  /**
   *  Establish connection with specified device trying different ports. Before using this method connection parameters such as ip, timeout, etc. must be specified (some of them can have default values). In this case, a list of ports will be passed as parameters. For each port of the list, the `connect` method will be called until the connection is established correctly.
   */
  connectWithIpAndPorts(ports: any[], waitFor: any[]): any;
  /** Closes IEC102 connection */
  disconnect(): any;
  /**
   *  Creates an array with values retrieved from pricing ASDUS. Finally created array is added to collection object.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  generateArrayDatastream(arrayId: string, sourceDatastream: string, asduResult: any, initialTime: number, finalTime: number, totalDays: number): any;
  /**
   *  Creates an array with values retrieved from load curve ASDUS. Finally created array is added to collection object.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  generateLoadCurveArrayDatastream(arrayId: string, sourceDatastream: string, asduResult: any, initialTime: number, finalTime: number, totalDays: number): any;
  /**
   *  Auxiliary function to calculate `period` object. This method only works if operations parameters match catalog parameters. It uses `iec102.referenceTime` and operation parameters.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getPeriodFromParams(): any;
  /**
   *  Auxiliary function internally used get an array with the names of steps to be executed for current operation. It matches operations steps list and defined ASDUs to be executed.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getSelectedSteps(): any[];
  /**
   *  Auxiliary function internally used to calculate if some asdu must be executed when defining ASDUs from operation parameters. It will be checked if the collected datastream fits specific conditions.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  mustExecute(ds: string, periodInitialTime: number, periodFinalTime: number): boolean;
  /**
   *  Calculates, if necessary, load curve incremental values from total values and vice versa.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  recalculateLoadCurves(asduResult: any, initialTime: number, finalTime: number): any;
  /** Sends a command. */
  send(command: string, waitFor: any[], pattern: string): any;
  /**
   *  Auxiliary function internally used set in the response the steps that are skipped.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  skipAllSelectedSteps(ds: string, stepDescription: string): any;
  /**
   *  Auxiliary function internally used to calculate connection speed.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  speed(): number;
  /**
   *  Auxiliary function internally to calculate if reading state to be collected is UNREAD.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  unreadOperation(): boolean;
  /**
   *  Parse operation parameters to check if they are valid catalog parameters for ASDUs calculation. This method is used internally to check if it is possible to calculate `period` and `asdusToExec` automatically from operations params.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  validCatalogParams(): any;
  asdus: {
    /**
     *  It is possible to add manually using `iec102.asdus.add` method. This method expect following parameters to define ASDU execution correctly:
     */
    add(name: any, execConfig: any): any;
    /**
     *  Calculates all ASDUs to be executed from operations parameters adding them to `asdus.asdusToExec` array. This method only works if parameters object has specific properties.
     */
    addFromParameters(): any;
    /** Execute directly `configuration` ASDU. */
    configuration(execConfig: any): any;
    /** Execute directly `currentPricing` ASDU. */
    currentPricing(execConfig: any): any;
    /** Execute directly `dayLightSavingTime` ASDU. */
    dayLightSavingTime(execConfig: any): any;
    /** Execute directly `deviceManufacturer` ASDU. */
    deviceManufacturer(execConfig: any): any;
    /** Execute one by one all the ASDUs defined in `asdus.asdusToExec`. */
    execute(): any;
    /** Execute directly `loadCurve` ASDU. */
    loadCurve(execConfig: any): any;
    /** Execute directly `loadCurveIncremental` ASDU. */
    loadCurveIncremental(execConfig: any): any;
    /** Execute directly `loadCurveIncrementalQuarter` ASDU. */
    loadCurveIncrementalQuarter(execConfig: any): any;
    /** Execute directly `loadCurveQuarter` ASDU. */
    loadCurveQuarter(execConfig: any): any;
    /** Execute directly `login` ASDU. */
    login(execConfig: any): any;
    /** Execute directly `logout` ASDU. */
    logout(execConfig: any): any;
    /** Execute directly `parameters` ASDU. */
    parameters(execConfig: any): any;
    /**
     *  Auxiliary function to fill response step for specific ASDU and send it if specified in stepBehaviour
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    processStep(stepBehaviour: any, asduResult: any): any;
    /** Execute directly `storedPricing` ASDU. */
    storedPricing(execConfig: any): any;
    /** It is possible to execute one asdu directly. For example: */
    timeRequest(): any;
  };
};

declare const kite: {
  /**
   *  Enable proxy.
   *  Default: false
   */
  proxyEnabled: boolean;
  /** Host of the proxy (if the proxy is enabled). */
  proxyHost: string;
  /** Port of the proxy (if the proxy is enabled). */
  proxyPort: number;
  /** Protocol of the proxy (if proxy is enabled). */
  proxyProtocol: string;
  /** Host of the Kite server. */
  uriHost: string;
  /** Service of the Kite server. */
  uriService: string;
  /**
   *  Changes the subscription status using the specified parameter and completes the collection object with a new administrative status.
   */
  requestChangeTerminalStatus(status: string): any;
  /** Gets the details of the subscription and complete collection object with result. */
  requestTerminalDetails(): any;
};

declare const logger: {
  /**
   *  Creates DEBUG level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  debug(...msg: any[]): void;
  /**
   *  Creates ERROR level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  error(...msg: any[]): void;
  /**
   *  Creates INFO level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  info(...msg: any[]): void;
  /**
   *  Creates TRACE level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  trace(...msg: any[]): void;
  /**
   *  Creates WARN level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  warn(...msg: any[]): void;
};

declare const mqtt: {
  /**
   *  Target device id
   *  Default: entity id
   */
  device: string;
  /**
   *  Topic uri where to publish the message
   *  Default: odm/request
   */
  topic: string;
  /** Publish a message on mqtt topic */
  publish(payload: any): any;
};

declare const operation: {
  /**
   *  **Read and return the selected device operations pending (with status WAITING_FOR_CONNECTION) of the user to execute the CFx**
   */
  getAllPending(): any;
  /** **Read and return the selected device operations that match a custom filter condition** */
  getByCustomCondition(customCondition: any): any;
  /** **Read and return the selected device operations that are not finished** */
  getNotFinished(): any;
};

declare const provision: {
  /** Creates a new entity in the platform. */
  create(fullBody?: any): any;
  /** Retrieves an existing entity from the database with specified identifier. */
  get(id?: string): any;
};

declare const response: {
  /**
   *  Builds a step result object and adds it to the steps list in the `response` global object.
   */
  addStep(name?: string, result?: string, description?: string, stepResponseList?: string): void;
  /** This method sets the `ERROR_IN_PARAM` statusCode with the provided description. */
  errorInParam(statusDescription: string): void;
  /** This method sets the `ERROR_PROCESSING` statusCode with the provided description. */
  errorProcessing(statusDescription: string): void;
  /** This method sets the `ERROR_TIMEOUT` statusCode with the provided description. */
  errorTimeout(statusDescription: string): void;
  /** This method sets the `NOT_SUPPORTED` statusCode with the provided description. */
  notSupported(statusDescription: string): void;
  /**
   *  Sends a step response message to the OpenGate's operation messages flow using the steps list in the `response` object, after that this list is cleaned.
   */
  sendSteps(): void;
  /** This method sets the `SUCCESSFUL` statusCode with the provided description. */
  successful(statusDescription: string): void;
  /** This method sets the `UNKNOWN_RESULT` statusCode with the provided description. */
  unknownResult(statusDescription: string): void;
};

declare const snmp: {
  /** Adds an OID to the list of OIDs to be retrieved/setted. */
  addOid(): any;
  /**
   *  Executes a multi SNMP get attribute request with specified payload. You must have previously given value to the properties `snmp.ip`, `snmp.port` (161 by default), `snmp.community` (in case of snmp version 1), `snmp.version` (3 by default), `snmp.retries` (3 by default), `snmp.timeout` (5000 by default) and security info in case of snmpv3 version (`snmp.securityName`, `snmp.authentication`, `snmp.privacy`, `snmp.authPassphrase` and `snmp.privPassphrase`).
   */
  get(): string;
  /**
   *  Executes a multi SNMP set attribute request with specified payload. You must have previously given value to the properties `snmp.ip`, `snmp.port` (161 by default), `snmp.community` (in case of snmp version 1), `snmp.version` (3 by default), `snmp.retries` (3 by default), `snmp.timeout` (5000 by default) and security info in case of snmpv3 version (`snmp.securityName`, `snmp.authentication`, `snmp.privacy`, `snmp.authPassphrase` and `snmp.privPassphrase`).
   */
  set(): string;
};

declare const ssh: {
  /** Rsa key content. */
  identity: string;
  /** IP address of the SSH server. */
  ip: string;
  /** SSH password. */
  password: string;
  /**
   *  Port of the SSH server.
   *  Default: 23
   */
  port: number;
  /**
   *  Number of retries.
   *  Default: 3
   */
  retries: number;
  /**
   *  Timeout in milliseconds.
   *  Default: 5000
   */
  timeout: number;
  /** SSH user. */
  user: string;
  /** Establish a connection with the SSH server. */
  connect(waitFor: any[]): any;
  /** Disconnects from the SSH server. */
  disconnect(): any;
  /** Sends a command to the SSH server and waits for the response. */
  send(command: string, pattern: string, waitFor: any[]): any;
};

declare const telnet: {
  /** IP address of the Telnet server. */
  ip: string;
  /**
   *  Port of the Telnet server.
   *  Default: 23
   */
  port: number;
  /**
   *  Number of retries.
   *  Default: 3
   */
  retries: number;
  /**
   *  Timeout in milliseconds.
   *  Default: 5000
   */
  timeout: number;
  /**
   *  Connects to the Telnet server using the properties of the Telnet object and the specified parameters.
   */
  connect(waitFor: string): any;
  /** Disconnects from the Telnet server. */
  disconnect(): any;
  /**
   *  Sends a command to the Telnet server and waits for the response with the specified parameters:
   */
  send(command: string, pattern: string, waitFor: string): any;
};

declare const utils: {
  atcmd: {
    /**
     *  Translates the response got by the 'AT+CSQ' command, which is the GSM signal strength and a numerical value, to its corresponding dBm value.
     */
    toDBm(value: number): number;
  };
  bytes: {
    /** **Kind**: global function */
    fromHexString(hexString: string): Uint8Array;
    /** **Kind**: global function */
    fromText(str: string): Uint8Array;
    /** **Kind**: global function */
    toHexString(array: any[]): string;
    /** **Kind**: global function */
    toText(bytes: any[]): string;
  };
  date: {
    period: {
      /** Calculates specified period in utc times in milliseconds. */
      customPeriodUtc(initialTimeStr: any, finalTimeStr: any): any;
      /**
       *  Calculates a period of defined days until reference time. If referenceTimeMillis is not defined, current time will be used as reference
       */
      lastDays(days: number, referenceTimeMillis: number): any;
      /**
       *  Calculates a period of defined hours until reference time. If referenceTimeMillis is not defined, current time will be used as reference
       */
      lastHours(hours: number, referenceTimeMillis: number): any;
      /**
       *  Calculates a period of defined minutes until reference time. If referenceTimeMillis is not defined, current time will be used as reference
       */
      lastMinutes(minutes: number, referenceTimeMillis: number): any;
      /** Calculates previous day from specified time in milliseconds. */
      previousDay(referenceTimeMillis: number): any;
      /** Calculates previous month from specified time in milliseconds. */
      previousMonth(referenceTimeMillis: number): any;
      /** Calculates previous quarter from specified time in milliseconds. */
      previousQuarter(referenceTimeMillis: number): any;
      /** Calculates previous week from specified time in milliseconds. */
      previousWeek(referenceTimeMillis: number): any;
    };
  };
  endesa: {
    /** Depending on the command value, specific translation will be returned. */
    commandFrom(command: string): string;
    /** If msisdn starts with "34", then returns the value without "34". */
    prepareMsisdn(msisdn: string): string;
    /** Example of use: */
    toDbmPlusQuality(value: string): any;
    /** Example of use: */
    torscp(value: string): any;
  };
  odm: {
    /**
     *  It can be used to add datastream in the Identification section of the OdmMessage, to relate the collected data with the subEntity; it is used with entities that have more than one CommunicationsCommsModule.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    addCollectionHint(key: string, value: string, structured: boolean): void;
    /**
     *  It can be used to add datastream in the Identification section of the OdmMessage, to identify the entity in Mongo Data Base.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    addIdentificationHint(key: string, value: string, structured: boolean): void;
    /** **Kind**: global function */
    addValueToContext(key: string, value: string): any;
    /**
     *  Decrypt an encrypted string with the configuration established by the datastream of the organization
     */
    decryptString(encryptedValue: string, datastreamConfiguration: string, organizationName: string): string;
    /**
     *  Encrypt an original string with the configuration established by the datastream of the organization
     */
    encryptString(originalValue: string, datastreamConfiguration: string, organizationName: string): string;
    /** Extract from the first entity of entities array specified datastream "value" field value. */
    entitiesValue(entities: any[], datastream: string, index?: number): any;
    /** Calculates the address type from a given address */
    getAddressTypeFromAddress(address: string): any;
    /** Executes specified request with specified payload. */
    httpRequest(request: any, payload?: any): any;
    /** Sleeps for specified time */
    sleep(time: number): any;
    db: {
      /**
       *  **The use of this function is discouraged.**
       *  @internal — the documentation marks this API as internal; it is not part of the public surface.
       */
      getEntity(identifier: string): any;
    };
  };
};

declare const websocket: {
  /** Device identifier with the opened websocket */
  deviceId: string;
  /** Data to be published. It will be converted to string. */
  payload: any;
  /** Executes specified request using the properties of the `websocket object` */
  sendMsg(): any;
};

