// Generated by tools/ogdocgen from the OpenGate documentation. DO NOT EDIT.
// context: provision-function
//
// Source pages:
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_actions_js_api.md
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_entities_js_api.md
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_errors_js_api.md
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_js_api.md
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_v8utils_js_api.md
//   content/api/management/organizations/channels/entities/bulk/provision_functions/provision_functions_v8utils_js_api_internal.md
//
// Regenerate: go run ./tools/ogdocgen -docs <odm-documentation-hugo> -out internal/typegen/templates

// ── Plain functions ─────────────────────────────────────────────────────────

/** Builds Create Asset action with provided JSON. */
declare function CREATE_ASSET_ACTION(entityJson: any, description: any): any;

/** Builds Create Device action with provided JSON. */
declare function CREATE_DEVICE_ACTION(entityJson: any, description: any): any;

/** Builds Create Subscriber action with provided JSON. */
declare function CREATE_SUBSCRIBER_ACTION(entityJson: any, description: any): any;

/** Builds Create Subscription action with provided JSON. */
declare function CREATE_SUBSCRIPTION_ACTION(entityJson: any, description: any): any;

/** Builds Delete Asset action with provided JSON. */
declare function DELETE_ASSET_ACTION(entityJson: any, description: any): any;

/** Builds Delete Device action with provided JSON. */
declare function DELETE_DEVICE_ACTION(entityJson: any, full: any, description: any): any;

/** Builds Delete Subscriber action with provided JSON. */
declare function DELETE_SUBSCRIBER_ACTION(entityJson: any, description: any): any;

/** Builds Delete Subscription action with provided JSON. */
declare function DELETE_SUBSCRIPTION_ACTION(entityJson: any, description: any): any;

/**
 *  Init `entityJson` property with an entity identifier. Use `new Entity(entityIdentifier)` to create a new Entity.
 */
declare function Entity(entityIdentifier: any): any;

/** Initialize ErrorManager entity. Use `new` keyword to create an instance of ErrorManager. */
declare function ErrorManager(platformErrors: any, actionObject: any, defaultErrorMessage: any): any;

/** Builds Patch Asset action with provided JSON. */
declare function PATCH_ASSET_ACTION(entityJson: any, description: any): any;

/** Builds Patch DEVICE action with provided JSON. */
declare function PATCH_DEVICE_ACTION(entityJson: any, description: any): any;

/** Builds Patch Subscriber action with provided JSON. */
declare function PATCH_SUBSCRIBER_ACTION(entityJson: any, description: any): any;

/** Builds Patch Subscription action with provided JSON. */
declare function PATCH_SUBSCRIPTION_ACTION(entityJson: any, description: any): any;

/** Builds Update Asset action with provided JSON. */
declare function UPDATE_ASSET_ACTION(entityJson: any, description: any): any;

/** Builds Update Device action with provided JSON. */
declare function UPDATE_DEVICE_ACTION(entityJson: any, description: any): any;

/** Builds Update Subscriber action with provided JSON. */
declare function UPDATE_SUBSCRIBER_ACTION(entityJson: any, description: any): any;

/** Builds Update Subscription action with provided JSON. */
declare function UPDATE_SUBSCRIPTION_ACTION(entityJson: any, description: any): any;

/** *Internal method.* */
declare function _checkDuplicatedDS(currentEntityIdentifierDatastream: any, currentEntityIdentifierValue: any, ...datastreamsToCheck: any[]): any;

/** *Internal method.* */
declare function _checkEntity(id: any, resourceType: any): any;

/** *Internal method.* */
declare function _createAction(action: any, entityJson: any, entityType: any, full: any, description: any): any;

/** Auxiliary method to build params maps for Java Queries */
declare function _minJavaParams(queryContextParams: any): any;

/** Check if an Asset exists for specified id. */
declare function checkAsset(id: any): any;

/** Check if a Device exists for specified id. */
declare function checkDevice(id: any): any;

/** Check if a Subscriber exists for specified id. */
declare function checkSubscriber(id: any): any;

/** Check if a Subscription exists for specified id. */
declare function checkSubscription(id: any): any;

/** Searches for duplicated datastreams in other Assets (other than currentAssetId). */
declare function duplicatedDsInAssets(currentAssetId: any, ...datastreamsToCheck: any[]): any;

/** Searches for duplicated datastreams in other Devices (other than currentDeviceId). */
declare function duplicatedDsInDevices(currentDeviceId: any, ...datastreamsToCheck: any[]): any;

/**
 *  Searches for duplicated datastreams in other Subscribers (other than currentSubscriberId).
 */
declare function duplicatedDsInSubscribers(currentSubscriberId: any, ...datastreamsToCheck: any[]): any;

/**
 *  Searches for duplicated datastreams in other Subscriptions (other than currentSubscriptionId).
 */
declare function duplicatedDsInSubscriptions(currentSubscriptionId: any, ...datastreamsToCheck: any[]): any;

/** Invokes Java V8 `genericSearchInternal` method for ENTITIES. */
declare function entitiesGenericSearch(searchFilter: any, queryContextParams: any): any;

/** Searches entities with provided filter. Your script calls it through */
declare function genericSearchInternal(searchTypeValue: any, searchQueryValue: any, javaParams: any): any;

/** Gets specific Asset for specified id. */
declare function getAssetEntity(id: any): any;

/** Gets specific Device for specified id. */
declare function getDeviceEntity(id: any): any;

/** Invokes Java V8 `getEntityInternal` method. */
declare function getEntity(entityId: any, resourceType: any, queryContextParams: any): any;

/** Gets specific Entity for provided id. Your script calls it through */
declare function getEntityInternal(provisionType: any, resourceType: any, entityId: any, javaParams: any): any;

/** Gets specific Subscriber for specified id. */
declare function getSubscriberEntity(id: any): any;

/** Gets specific Subscription for specified id. */
declare function getSubscriptionEntity(id: any): any;

/** Creates Entity class object with specified entity json. */
declare function newEntityBuilder(fromEntityJson: any): any;

/** Invokes Java V8 `printLogInternal` method. */
declare function printLog(msg: any): any;

/**
 *  Writes INFO log messages. Your script calls it through [printLog](../provision_functions_v8utils_js_api/#printlogmsg).
 */
declare function printLogInternal(msg: any): any;

/** Auxiliary method to read values from the specified map. */
declare function readMapValue(map: any, headerName: any, defaultValue: any, headerColumn: any): any;

// ── Objects ─────────────────────────────────────────────────────────────────

/** Accessor methods carried by `entity`, intersected into its declaration. */
interface OGEntityMethods {
  /** *Internal method.* */
  _addToEntity(datastream: any): any;
  /** *Internal method.* */
  _cleanArray(valuesArray: any): any;
  /** *Internal method.* */
  _generateDatastreamEntry(datastream: any, dsJson: any): any;
  /** *Internal method.* */
  _generateDatastreamJsonWithArray(datastream: any, valuesArray: any): any;
  /** *Internal method.* */
  _generateDatastreamWithJson(datastream: any, value: any): any;
  /** *Internal method.* */
  _generateIndexedJson(index: any, value: any): any;
  /** *Internal method.* */
  _generateJsonCurrentValue(value: any): any;
  /** Method to be used to add datastreams to current entity. */
  addDatastream(datastream: any, value: any, _index: any): any;
  /**
   *  Delete specified datastream. This function requires always complete datastream (ignores withPrefix functions calls).
   */
  deleteDatastream(datastream: any, _index: any): any;
  /**
   *  Search specified datastream and returns value. This function requires always complete datastream (ignores withPrefix functions calls).
   */
  getDatastream(datastream: any, _index: any): any;
  /** Define the prefix of the datastreams to be used by `addDatastream` method. */
  withPrefix(prefixToBeUsed: any): any;
}

declare const errorManager: {
  /** Returns provision action type (POST, PUT, PATCH, DELETE) from OdmProvisionAction */
  getAction(): any;
  /** Returns entity administration identifier. */
  getAdministrationIdentifier(): any;
  /**
   *  Returns from entity (in OdmProvisionAction) specific datastream value (datastream._value._current.value). It can be an object or plain string.
   */
  getDatastreamValue(index: any): any;
  /**
   *  Returns from entity (in OdmProvisionAction) specific datastream value (datastream._value._current.value). It can be a json string.
   */
  getDatastreamValueAsString(index: any): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  getDefaultMessage(): any;
  /**
   *  Returns provision entity type (asset, device, subscription, subscriber) from OdmProvisionAction
   */
  getEntityType(): any;
  /** Returns number of errors contained. */
  getErrorsSize(): any;
  /** Returns first error's first context object. */
  getFirstContext(): any;
  /** Returns first error's first context object as string. */
  getFirstContextAsString(): any;
  /** Returns first error's first context's name property. */
  getFirstContextName(): any;
  /** Returns first error's first context's value property. */
  getFirstContextValue(): any;
  /** Returns first error object. */
  getFirstError(): any;
  /** Returns first error object as string */
  getFirstErrorAsString(): any;
  /** Returns first error's code property. */
  getFirstErrorCode(): any;
  /** Returns first error's context property. */
  getFirstErrorContextArray(): any;
  /** Returns first error's context property. */
  getFirstErrorContextArrayAsString(): any;
  /** Returns first error's message property. */
  getFirstErrorMessage(): any;
  /** Returns specific context in specific error. */
  getSpecificContext(errorIndex: any, contextIndex: any): any;
  /** Returns specific context in specific error as string. */
  getSpecificContextAsString(errorIndex: any, contextIndex: any): any;
  /** Returns specific context's name in specific error. */
  getSpecificContextName(errorIndex: any, contextIndex: any): any;
  /** Returns specific context's value in specific error. */
  getSpecificContextValue(errorIndex: any, contextIndex: any): any;
  /** Returns specific error's code */
  getSpecificErrorCode(index: any): any;
  /** Returns specific error's context property as array. */
  getSpecificErrorContextArray(index: any): any;
  /** Returns specific error's context property as string. */
  getSpecificErrorContextArrayAsString(index: any): any;
  /** Returns specific error's message */
  getSpecificErrorMessage(index: any): any;
  /** Returns specific error object */
  getSpecificErrorObject(index: any): any;
  /** Returns specific error object as a string */
  getSpecificErrorObjectAsString(index: any): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isAsset(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isDelete(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isDevice(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isPatch(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isPost(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isPut(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isSubscriber(): any;
  /** **Kind**: instance method of [ErrorManager](#errormanager) */
  isSubscription(): any;
};

