// Generated by tools/ogdocgen from the OpenGate documentation. DO NOT EDIT.
// context: rule-advanced
//
// Source pages:
//   content/api/management/organizations/channels/rules/rules_advanced_actions_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_alarms_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_cypher_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_datastreams_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_dates_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_notifications_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_operations_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_provision_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_utils_api.md
//   content/api/management/organizations/channels/rules/rules_internal_js_functions.md
//
// Regenerate: go run ./tools/ogdocgen -docs <odm-documentation-hugo> -out internal/typegen/templates

// ── Plain functions ─────────────────────────────────────────────────────────

/** > **Deprecated:** Use `notification` object functions instead. */
declare function addEmailNotification(recipients: any, notificationName: any, notificationBody: any, ruleName: any, mailParameters: any): any;

/** > **Deprecated:** Use `notification` object functions instead. */
declare function addTrapNotification(recipients: any, variables: any, notificationName: any, trapOID: any, enterpriseOID: any, ruleName: any): any;

/**
 *  Check if 2 arrays are equals
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function arrayEquals(array1: any[], array2: any[]): any;

/** > **Deprecated:** Use `utils` object functions instead. */
declare function cancelDelay(ruleName: any): any;

/**
 *  > **Deprecated:** Use `utils` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function cancelJobGroup(ruleName: any): any;

/** > **Deprecated:** Use `alarm` object functions instead. */
declare function closeAlarmByAlarmName(entityIdDatastream: any, alarmName: any): any;

/** > **Deprecated:** Use `alarm` object functions instead. */
declare function closeAlarmByRuleName(entityIdDatastream: any, ruleName: any): any;

/**
 *  > **Deprecated:** Use `collect` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function collectDataPoints(resourceType: any, identifier: any, mapValues: any, commsValues: any, ttl: any): any;

/**
 *  > **Deprecated:** Use `collect` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function collectDatastreams(jsMapValues: any, jsCommsValues: any, directMode: any, reinject: any): any;

/** > **Deprecated:** Use `utils` object functions instead. */
declare function decryptString(encryptedValue: any, datastreamId: any, organization: any): any;

/** > **Deprecated:** Use `utils` object functions instead. */
declare function encryptString(originalValue: any, datastreamId: any, organization: any): any;

/** > **Deprecated:** Use `operation` object functions instead. */
declare function executeOperation(subEntityIdentifier: any, operationType: any, operationTimeout: any, jobUser: any, retries: any, ackTimeout: any, retriesDelay: any, stopValue: any, stopMode: any, parameters: any, callback: any): any;

/**
 *  > **Deprecated:** Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getAreas(coordinates: any[]): any;

/** Returns complete datastream in selected communication module of received entity. */
declare function getCommsDatastreamFromEntity(datastreamId: any, commsId: any): any;

/**
 *  Obtains `incValue` if `datastreamValue` date is before than `resetDate` or increments received value in datastream to `incValue` if the date is after.
 */
declare function getCounterValue(datastreamValue: any, incValue: any, resetDate: any): any;

/**
 *  Same as getCounterValue, but returns an object with the counter value, a flag indicating whether the reset was activated, and the previous value
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getCounterValueWithReset(datastreamValue: any, incValue: number, resetDate: Date): any;

/**
 *  Gets the incremented value of the read datastream if its date is before the date obtained by function _getDailyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromDB(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Same as _getDailyCounterValueFromDB_ but returning the object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromDBWithReset(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Gets the incremented value of the received datastream if its date is before the date obtained by function _getDailyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromMessage(datastream: any, incValue: number): any;

/**
 *  Same as _getDailyCounterValueFromMessage_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromMessageWithReset(datastream: any, incValue: number): any;

/** Obtains date to reset daily counters. */
declare function getDailyResetDate(): any;

/** Obtains date to reset daily counters with defined hour in gmt+0. */
declare function getDailyResetDateWithZuluHour(hour: any): any;

/**
 *  > **Deprecated:** Use `utils` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDatastreamByIdFromDB(datastreamId: OGDatastreamID, subEntityIdentifier: string): any;

/** This method returns completed datastream of received entity. */
declare function getDatastreamFromEntity(datastreamId: OGDatastreamID): any;

/**
 *  Get datastream object in communicationModules datastream (check that this datastreams is array and not object) selecting index of array.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDatastreamValueCmmsModuleFromEntity(datastreamObject: any, position: number): any;

/** Returns `_value._current._value` from datastream object */
declare function getDatastreamValueFromEntity(datastreamObject: any): any;

/**
 *  > **Deprecated:** Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDistance(lat1: number, long1: number, lat2: number, long2: number): any;

/**
 *  Gets the incremented value of the read datastream if its date is before the date obtained by function _getMonthlyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromDB(datastreamId: string, incValue: number, subEntityIdentifier: string): any;

/**
 *  Same as _getMonthlyCounterValueFromDB_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromDBWithReset(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Gets the incremented value of the received datastream if its date is before the date obtained by function _getMonthlyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromMessage(datastream: any, incValue: number): any;

/**
 *  Same as _getMonthlyCounterValueFromMessage_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromMessageWithReset(datastream: any, incValue: number): any;

/** Obtains date to reset monthly counters. */
declare function getMonthlyResetDate(): any;

/** Obtains date to reset monthly counters with defined hour in gmt+0. */
declare function getMonthlyResetDateWithZuluHour(hour: any): any;

/** Obtains date to reset monthly counters with defined hour in gmt+0. */
declare function getMonthlyResetDateWithZuluHourAndDayOfMonth(hour: any, dayOfMonth: any): any;

/**
 *  > **Deprecated:** Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getSortedAreas(coordinates: any[], sorted: boolean): any;

/** This method reads a variable value. */
declare function getVariableValue(variable: any): any;

/**
 *  Obtains if message is from insert provision action
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isInsertAction(entity?: any): any;

/**
 *  Obtains if message is from patch provision action
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isPatchAction(entity?: any): any;

/**
 *  Obtains if message is from update provision action
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isUpdateAction(entity?: any): any;

/** > **Deprecated:** Use `alarm` object functions instead. */
declare function openAlarm(subEntityIdentifier: any, alarmName: any, ruleName: any, severity: OGSeverity, priority: OGPriority, alarmDescription: any, extraInfo: any): any;

/**
 *  > **Deprecated:** Use `alarm` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function openAlarmWithExtraInfo(subEntityIdentifier: any, alarmName: any, ruleName: any, severity: OGSeverity, priority: OGPriority, alarmDescription: any, extra_info: any): any;

/**
 *  > **Deprecated:** Use `logger` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function printLog(log: any): any;

/** > **Deprecated:** Use `notification` object functions instead. */
declare function sendHttp(httpJson: any): any;

/** Obtain date type from string date representation with format YYYY-MM-DDThh:mm:ssTZD. */
declare function toDate(localDateTime: any): any;

// ── Objects ─────────────────────────────────────────────────────────────────

declare const alarm: {
  /** Closes alarm by alarm name. */
  closeByAlarmName(closeByNameConfig: any): any;
  /** Closes alarm by rule name. */
  closeByRuleName(closeByRuleConfig: any): any;
  /** Opens an alarm. */
  open(alarmConfig: OGAlarmConfig): any;
};

declare const collect: {
  /**
   *  Collect datapoints in received entity
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  datapoints(datapointConfig: any): any;
  /**
   *  Collect values in received entity
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  datastreams(datastreamConfig: any): any;
};

declare const http: {
  client: {
    /**
     *  Send DELETE http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    delete_(): any;
    /**
     *  Send GET http method.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    get(): any;
    /**
     *  Send PATCH http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    patch(): any;
    /**
     *  Send POST http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    post(): any;
    /**
     *  Send PUT http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    put(): any;
    /**
     *  Send an HTTP request with the method defined in the `method` property, which must be set before calling this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    request(): any;
  };
};

declare const location: {
  /**
   *  Get provisioned areas in OpenGate to selected coordinate.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getAreas(coordinates: any[]): any;
  /**
   *  Get distance between 2 coordinates in meters.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getDistance(lat1: number, long1: number, lat2: number, long2: number): any;
  /**
   *  Same as getAreas but is possible get sorted by ordered field.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getSortedAreas(coordinates: any[], sorted: boolean): any;
};

declare const notification: {
  /** Sends an email notification to defined recipients. */
  addEmailNotification(emailConfig: any): any;
  /** Sends an SNMP trap notification to defined recipients. */
  addTrapNotification(trapConfig: any): any;
  /** Sends an HTTP request notification to a specified URL. */
  sendHttp(httpConfig: any): any;
};

declare const operation: {
  /** Execute selected operation to received identifier. */
  execute(operationConfig: any): any;
};

declare const provision: {
  /** **Returns**: void */
  datastreams(provisionConfig: any): any;
};

declare const utils: {
  /** Cancels an active delayed action produced by another rule activation. */
  cancelDelay(ruleName: string): any;
  /** Decrypt a value. */
  decryptString(decryptConfig: any): any;
  /** Encrypt a value. */
  encryptString(encryptConfig: any): any;
  /**
   *  Get datastream reading from DB.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getDatastreamByIdFromDB(datastreamId: string, subEntityIdentifier: string): any;
};

