// Generated by tools/ogdocgen from the OpenGate documentation. DO NOT EDIT.
// context: rule-advanced
//
// Source pages:
//   content/api/management/organizations/channels/rules/rules_advanced_actions_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_alarms_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_cypher_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_datastreams_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_dates_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_notifications_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_operations_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_provision_api.md
//   content/api/management/organizations/channels/rules/rules_advanced_utils_api.md
//   content/api/management/organizations/channels/rules/rules_internal_js_functions.md
//
// Regenerate: go run ./tools/ogdocgen -docs <odm-documentation-hugo> -out internal/typegen/templates

// ── Plain functions ─────────────────────────────────────────────────────────

/**
 *  Sends email notification to defined recipients.
 *  @deprecated Use `notification` object functions instead.
 */
declare function addEmailNotification(recipients: any[], notificationName: string, notificationBody: string, ruleName: string, mailParameters: any): void;

/**
 *  Sends trap notification to defined recipients.
 *  @deprecated Use `notification` object functions instead.
 */
declare function addTrapNotification(recipients: any[], variables: any, notificationName: string, trapOID: string, enterpriseOID: string, ruleName: string): void;

/**
 *  Check if 2 arrays are equals
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function arrayEquals(array1: any[], array2: any[]): boolean;

/**
 *  Cancels active delayed action produced by another rule activation.
 *  @deprecated Use `utils` object functions instead.
 */
declare function cancelDelay(ruleName: string): void;

/**
 *  Cancels an active delayed action produced by another rule activation.
 *  @deprecated Use `utils` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function cancelJobGroup(ruleName: any): any;

/**
 *  Closes an alarm for the selected entity using alarm name.
 *  @deprecated Use `alarm` object functions instead.
 */
declare function closeAlarmByAlarmName(entityIdDatastream: string, alarmName: string): void;

/**
 *  Closes an alarm for the selected entity using rule name.
 *  @deprecated Use `alarm` object functions instead.
 */
declare function closeAlarmByRuleName(entityIdDatastream: string, ruleName: string): void;

/**
 *  Collect datapoints in received entity
 *  @deprecated Use `collect` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function collectDataPoints(resourceType: any, identifier: any, mapValues: any, commsValues: any, ttl: any): any;

/**
 *  Collect values in received entity
 *  @deprecated Use `collect` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function collectDatastreams(jsMapValues: any, jsCommsValues: any, directMode: any, reinject: any): any;

/**
 *  Decrypt an encrypted string with the configuration established by the datastream of the organization
 *  @deprecated Use `utils` object functions instead.
 */
declare function decryptString(encryptedValue: string, datastreamId: string, organization: string): string;

/**
 *  Encrypt an original string with the configuration established by the datastream of the organization
 *  @deprecated Use `utils` object functions instead.
 */
declare function encryptString(originalValue: string, datastreamId: string, organization: string): string;

/**
 *  Executes selected operation to received identifier.
 *  @deprecated Use `operation` object functions instead.
 */
declare function executeOperation(subEntityIdentifier: string, operationType: string, operationTimeout?: number, jobUser?: string, retries?: number, ackTimeout?: number, retriesDelay?: number, stopValue?: number, stopMode?: string, parameters?: any, callback?: string): void;

/**
 *  Get provisioned areas in OpenGate to selected coordinate.
 *  @deprecated Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getAreas(coordinates: any[]): any;

/** Returns complete datastream in selected communication module of received entity. */
declare function getCommsDatastreamFromEntity(datastreamId: string, commsId: string): any;

/**
 *  Obtains `incValue` if `datastreamValue` date is before than `resetDate` or increments received value in datastream to `incValue` if the date is after.
 */
declare function getCounterValue(datastreamValue: any, incValue: number, resetDate: Date): number;

/**
 *  Same as getCounterValue, but returns an object with the counter value, a flag indicating whether the reset was activated, and the previous value
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getCounterValueWithReset(datastreamValue: any, incValue: number, resetDate: Date): any;

/**
 *  Gets the incremented value of the read datastream if its date is before the date obtained by function _getDailyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromDB(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Same as _getDailyCounterValueFromDB_ but returning the object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromDBWithReset(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Gets the incremented value of the received datastream if its date is before the date obtained by function _getDailyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromMessage(datastream: any, incValue: number): any;

/**
 *  Same as _getDailyCounterValueFromMessage_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDailyCounterValueFromMessageWithReset(datastream: any, incValue: number): any;

/** Obtains date to reset daily counters. */
declare function getDailyResetDate(): Date;

/** Obtains date to reset daily counters with defined hour in gmt+0. */
declare function getDailyResetDateWithZuluHour(hour: string): Date;

/**
 *  Get datastream reading from DB.
 *  @deprecated Use `utils` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDatastreamByIdFromDB(datastreamId: OGDatastreamID, subEntityIdentifier: string): any;

/** This method returns completed datastream of received entity. */
declare function getDatastreamFromEntity(datastreamId: OGDatastreamID): any;

/**
 *  Get datastream object in communicationModules datastream (check that this datastreams is array and not object) selecting index of array.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDatastreamValueCmmsModuleFromEntity(datastreamObject: any, position: number): any;

/** Returns `_value._current._value` from datastream object */
declare function getDatastreamValueFromEntity(datastreamObject: any): any;

/**
 *  Get distance between 2 coordinates in meters.
 *  @deprecated Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getDistance(lat1: number, long1: number, lat2: number, long2: number): any;

/**
 *  Gets the incremented value of the read datastream if its date is before the date obtained by function _getMonthlyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromDB(datastreamId: string, incValue: number, subEntityIdentifier: string): any;

/**
 *  Same as _getMonthlyCounterValueFromDB_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromDBWithReset(datastream: any, incValue: number, subEntityIdentifier: string): any;

/**
 *  Gets the incremented value of the received datastream if its date is before the date obtained by function _getMonthlyResetDate_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromMessage(datastream: any, incValue: number): any;

/**
 *  Same as _getMonthlyCounterValueFromMessage_ but returning object of _getCounterValueWithReset_
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getMonthlyCounterValueFromMessageWithReset(datastream: any, incValue: number): any;

/** Obtains date to reset monthly counters. */
declare function getMonthlyResetDate(): Date;

/** Obtains date to reset monthly counters with defined hour in gmt+0. */
declare function getMonthlyResetDateWithZuluHour(hour: string): Date;

/** Obtains date to reset monthly counters with defined hour in gmt+0. */
declare function getMonthlyResetDateWithZuluHourAndDayOfMonth(hour: string, dayOfMonth: number): Date;

/**
 *  Same as getAreas but is possible get sorted by ordered field.
 *  @deprecated Use `location` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function getSortedAreas(coordinates: any[], sorted: boolean): any;

/** This method reads a variable value. */
declare function getVariableValue(variable: any): any;

/**
 *  Obtains if message is from insert provision action.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isInsertAction(): boolean;

/**
 *  Obtains if message is from patch provision action.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isPatchAction(): boolean;

/**
 *  Obtains if message is from update provision action.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function isUpdateAction(): boolean;

/**
 *  Opens an alarm for the selected entity.
 *  @deprecated Use `alarm.open` instead, which takes a single configuration object. **This function takes no extra information**: a seventh argument is ignored by the platform. The `alarm.open` object carries an `extraInfo` field, which is where that data belongs now.
 */
declare function openAlarm(subEntityIdentifier: string, alarmName: string, ruleName: string, severity: OGSeverity, priority: OGPriority, alarmDescription: string): void;

/**
 *  Same as _openAlarm_ adding extraInfo parameter.
 *  @deprecated Use `alarm` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function openAlarmWithExtraInfo(subEntityIdentifier: any, alarmName: any, ruleName: any, severity: OGSeverity, priority: OGPriority, alarmDescription: any, extra_info: any): any;

/**
 *  Show in traces log object
 *  @deprecated Use `logger` object functions instead.
 *  @internal — the documentation marks this API as internal; it is not part of the public surface.
 */
declare function printLog(log: any): any;

/**
 *  Sends http notification to defined recipients.
 *  @deprecated Use `notification` object functions instead.
 */
declare function sendHttp(httpJson: any): void;

/** Obtain date type from string date representation with format YYYY-MM-DDThh:mm:ssTZD. */
declare function toDate(localDateTime: string): Date;

// ── Objects ─────────────────────────────────────────────────────────────────

declare const alarm: {
  /** Closes alarm by alarm name. */
  closeByAlarmName(closeByNameConfig: any): void;
  /** Closes alarm by rule name. */
  closeByRuleName(closeByRuleConfig: any): void;
  /** Opens an alarm. */
  open(alarmConfig: OGAlarmConfig): void;
};

declare const collect: {
  /**
   *  Collect datapoints in received entity
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  datapoints(datapointConfig: any): any;
  /**
   *  Collect values in received entity
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  datastreams(datastreamConfig: any): any;
};

declare const http: {
  client: {
    /**
     *  Send DELETE http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    delete_(): any;
    /**
     *  Send GET http method.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    get(): any;
    /**
     *  Send PATCH http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    patch(): any;
    /**
     *  Send POST http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    post(): any;
    /**
     *  Send PUT http method. Property `method` is overridden by this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    put(): any;
    /**
     *  Send an HTTP request with the method defined in the `method` property, which must be set before calling this function.
     *  @internal — the documentation marks this API as internal; it is not part of the public surface.
     */
    request(): any;
  };
};

declare const location: {
  /**
   *  Get provisioned areas in OpenGate to selected coordinate.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getAreas(coordinates: any[]): any;
  /**
   *  Get distance between 2 coordinates in meters.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getDistance(lat1: number, long1: number, lat2: number, long2: number): any;
  /**
   *  Same as getAreas but is possible get sorted by ordered field.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getSortedAreas(coordinates: any[], sorted: boolean): any;
};

declare const notification: {
  /** Sends an email notification to defined recipients. */
  addEmailNotification(emailConfig: any): void;
  /** Sends an SNMP trap notification to defined recipients. */
  addTrapNotification(trapConfig: any): any;
  /** Sends an HTTP request notification to a specified URL. */
  sendHttp(httpConfig: any): void;
};

declare const operation: {
  /** Execute selected operation to received identifier. */
  execute(operationConfig: any): void;
};

declare const provision: {
  /** This function takes as parameter an object with the following fields: */
  datastreams(provisionConfig: any): void;
};

declare const utils: {
  /** Cancels an active delayed action produced by another rule activation. */
  cancelDelay(ruleName: string): void;
  /** Decrypt a value. */
  decryptString(decryptConfig: any): string;
  /** Encrypt a value. */
  encryptString(encryptConfig: any): string;
  /**
   *  Get datastream reading from DB.
   *  @internal — the documentation marks this API as internal; it is not part of the public surface.
   */
  getDatastreamByIdFromDB(datastreamId: string, subEntityIdentifier: string): any;
};

