// Generated by tools/ogdocgen from the OpenGate documentation. DO NOT EDIT.
// context: timeseries-function
//
// Source pages:
//   content/api/data_retrieval/time_series/timeseries_functions/aggregation_functions_js_api.md
//
// Regenerate: go run ./tools/ogdocgen -docs <odm-documentation-hugo> -out internal/typegen/templates

// ── Objects ─────────────────────────────────────────────────────────────────

declare const aggFunct: {
  /**
   *  The engine will calculate the arithmetic average of all received values in the configured time bucket. Only available in numeric values.
   */
  AVG(receivedValues: any[], currentValue: any, extra: any): any;
  /** The engine will store the count of total number values received per time bucket. */
  COUNT(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will store only the first received value per time bucket. The collection engine ignores the following values obtained in the same time bucket.
   */
  FIRST(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will calculate the geometric average of all received values in the configured time bucket. Only available in numeric values.
   */
  GEO_AVG(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will store only the last received value per time bucket, overwriting the previous ones.
   */
  LAST(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will save the maximum value of all received values in the configured time bucket. Only available for numeric values.
   */
  MAX(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will calculate the median of all received values in the configured time bucket. Only available in numeric values.
   */
  MEDIAN(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will save the minimum value of all received values in the configured time bucket. Only available for numeric values.
   */
  MIN(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will calculate the standard deviation of all received values in the configured time bucket. Only available in numeric values.
   */
  STD_DEVIATION(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will save the sum of all received values in the configured time bucket. Only available for numeric values.
   */
  SUM(receivedValues: any[], currentValue: any, extra: any): any;
  /**
   *  The engine will calculate the variance of all received values in the configured time bucket. Only available in numeric values.
   */
  VARIANCE(receivedValues: any[], currentValue: any, extra: any): any;
};

declare const data: {
  /**
   *  Aux method to check if some value has value. If value is `undefined` or `null` it will return false.
   */
  exists(value: any): boolean;
  /**
   *  Aux method to replace all undefined fields with null values. Internally used to avoid issues when processing execution result.
   */
  undefined2null(value: any): any;
};

declare const date: {
  /**
   *  Compares two dates. These dates can be passed as strings in ISO format or as Date objects. The result is:
   */
  compare(date1: Date, date2: Date): any;
  /** Create Date object from ISO string. */
  fromString(stringDate: string): any;
  /** Returns iso string representation of Date object. */
  toString(date: Date): any;
};

declare const log: {
  /**
   *  Creates *DEBUG* level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  debug(...msg: any[]): any;
  /**
   *  Creates *ERROR* level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  error(...msg: any[]): any;
  /**
   *  Creates *INFO* level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  info(...msg: any[]): any;
  /**
   *  Creates *TRACE* level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  trace(...msg: any[]): any;
  /**
   *  Creates *WARN* level logging messages. It concatenates msg parameters to compound message to be logged.
   */
  warn(...msg: any[]): any;
};

declare const result: {
  /**
   *  Internally used to build aggregation function result object when some execution exception is caught.
   */
  error(error: any): any;
  /** Used to build aggregation function result object */
  ok(value: any, ...extraParams: any[]): any;
};

